- package.json
NPM does this for you! :smile:
> No need to prepend `node_modules` path

- README.md
Also removed references to (missing) home component
> Updated reference of .js files to .ts files

- src/app/components/home/home.ts
> fix(home.ts): fix minor typo

- webpack.config.js
Minor updates in webpack.config.js
> Get rid of code duplications in webpack.config.js

- src/app/components/rxjs-examples/autosuggest/Search.ts
[https://github.com/angular-class/angular2-webpack-starter/issues/35](https://github.com/angular-class/angular2-webpack-starter/issues/35)
> Fix wrong case in file reference

- README.md
Fix minor typo and add tic-tac-toe to rxjs-examples
> chore(README.md): Fix typo and add tic-tac-toe

- README.md
- src/app/components/app.ts
- src/app/components/rxjs-examples/rxjs-examples.ts
Use only new router for nested routes and remove the workaround with ng-if
> chore(rxjs-examples.ts): Use new router for nested routes

- src/app/components/rxjs-examples/rxjs-examples.ts
- webpack.config.js
Proper highlighting of selected menu item
> chore(rxjs-examples): fix menu item selection

- package.json
> Update karma-webpack to 1.7.0

- README.md
> docs: typo fix in README.md

- src/typings/ng2.d.ts
I don't like to see red errors in my Webstorm :P
> fix(typings): missing semi-colons

- src/app/app.ts
Fixes #81 and makes use of the component in the footer to better demonstrate its usage.
> Fix: x-large component style

- protractor.conf.js
> Version update for selenium-server

- examples/game-tictactoe/components/board/board.ts
Fixes https://github.com/angular-class/angular2-webpack-starter/issues/108
> Change: properties => inputs, events => outputs

- karma.conf.js
> chore(tests): use ts-loader

- examples/game-tictactoe/app.ts
- examples/game-tictactoe/bootstrap.ts
- examples/game-tictactoe/components/board/board.ts
- examples/game-tictactoe/components/tictactoe.ts
- examples/game-tictactoe/services/GameService.ts
- stop importing `angular2/debug`
- replace `_BINDINGS` with `_PROVIDERS`
- replace deprecated `bind()` with `provide()`
- remove unnecessary `@View`
> update tictactoe game

- examples/rx-draggable/directives/draggable.ts
Use public method toRx() of EventEmitter insted of _subject.
> fix(draggable.ts): Use toRx() of EventEmitter

- spec.bundle.js
- test/app/app.spec.ts
See https://github.com/AngularClass/angular2-webpack-starter/pull/128#discussion-diff-44580177
> Move browser dom adapter setup to spec.bundle.js

- package.json
- spec-bundle.js
Hi guys, 
Karma test just can't work as is. 
I suggest this quick fix to ensure they can be launched.
Best regards,
Michel.
> Fix : polyfill added for phantomjs as needed for karma tests.

- test/injector.spec.ts
> Changed angular2 to angular2/core

- package.json
tslint-loader depends on tslint
> Add tslint as dependecy in package.json

- README.md
I know typo-pr's are lame, but PR is quicker than sending email ;)
> Typo: form -> from

- package.json
- webpack.prod.config.js
* Compresses `*.css`, `*.html`, `*.js` and `*.map` build assets
* Uses gzip with maximum compression level - 9
Closes #234
> feat(webpack): add compression plugin

- tsconfig.json
> fix(tsconfig): add typings/main.d.ts to filesGlob

- package.json
> Added reference to src folder for server:dev

- package.json
> chore: fix angular2 dependencies

- README.md
The dir structure looks actually a little different ;)
> Fix a mini-typo

- typings.json
> fix(typings.json): Wrong zone url

- README.md
> Fixing a typo inside README 

- tslint.json
Fixed small typo in TSLint configuration.
> Fix indent rule config in tslint.json

- webpack.prod.config.js
See fix in:
https://github.com/AngularClass/angular2-webpack-starter/issues/374
> Fix production build for now (tslint error)

- src/app/directives/router-active.ts
Fixing:
ERROR in ./src/app/directives/router-active.ts
[53, 36]: missing whitespace
[61, 25]: missing whitespace
> Tslint fails over the whitespace in the production build

- README.md
We need to install global libraries `typings ` and `webpack-dev-server` before start server
> Add more info to quick start section

- webpack.test.config.js
> Fixed error when running tests

- src/app/home/home.ts
Updates a comment that *seems* to be old.
No behavior change.
No behavior change.
None.
> docs(home component): change probably forgotten comment

- webpack.prod.config.js
> chore(webpack.prod): correct app designation

- webpack.config.js
- webpack.prod.config.js
- webpack.test.config.js
Comments cleanup
It's the same as before
It's the same as before
- Moved some variables to constants. 
- Reordered plugins initialization headers
> Webpack configuration cleanup

- src/app/app.component.ts
Fixed e2e task by adding the header element in the template of the app
e2e tests fail
e2e tests pass
> Fixed e2e tests by adding the header element

- config/helpers.js
Code cleanup
This PR doesn't affect any behavior. It just removes an unreachable piece of code.
This PR doesn't affect any behavior. It just removes an unreachable piece of code.
> Remove unreachable code

- package.json
- src/app/app.component.ts
Feature: use normalize.css to reset browser
> introduce normalize.css

- src/platform/browser/angular2-material2/index.ts
Fix for radio button of angular material.
> Added MdRadioGroup (it was throwing an error without)

- package.json
unit tests should be run before end to end tests
> unit tests before e2e tests

- config/webpack.common.js
Remove dead code
The alias 'angular2/testing' does not work
The alias 'angular2/testing' will be work correctly
> Removed duplication of alias `angular2/testing`

- src/platform/browser/providers.ts
Deleted an unused import line.
> chore: remove unused import

- README.md
docs update
info in quickstart but missing in ##installation
added to ##installation of readme
> add globals to ##installing

- config/spec-bundle.js
Bug fix
Cannot run fakeAsync tests, see issue #590 
fakeAsync tests run successfully. Sync tests may also be effected so this PR also adds the relevant zone file.
> fix fakyAsync and sync test

- config/spec-bundle.js
> Cleaning up comment typos

- config/webpack.common.js
* **What kind of change does this PR introduce?** Updating comments only.
* **Other information**: This seems more readable and hopefully better tracks the commenting patterns used elsewhere in the project (i.e. one comment describing each option, with the option itself commented out separately).
> Separate comment blocks for each option

- package.json
> add keywords

- package.json
> fix npm run lint

- .github/CONTRIBUTING.md
The essence is in the title: fixed typo and polished text a little bit.
> Fixed typo and polished text in CONTRIBUTING.md

- package.json
Bug fix
#712  Double dependence on istanbul-instrumenter-loader in package.json 
> Remove a duplicate dev dependency

- config/webpack.dev.js
- package.json
- src/app/+detail/detail.component.ts
- src/app/+detail/index.component.ts
- src/app/+detail/routes.ts
- src/app/about/about.component.ts
- src/app/about/about.spec.ts
- src/app/app.component.ts
- src/app/app.resolver.ts
- src/app/app.routes.ts
- src/app/app.spec.ts
- src/app/app.style.css
- src/app/home/home.spec.ts
- src/app/home/home.style.css
- src/app/home/title/title.spec.ts
- src/custom-typings.d.ts
- src/platform/browser-providers.ts
- src/platform/environment.ts
- src/vendor.browser.ts
- tsconfig.json
branch merge
material2 branch is falling further behind master
merge master into material2 branch to keep material2 branch up-to-date
I assume that the travis ci builds will fail for this pr due to the fact that the official material2 components refer to the previous core rc and forms package in peer dependencies, i think there might be some issues introduced in rc4 that might have prevented an immediate update to the official material package. however, i have not noticed anything broken when updating this repo to use the latest rc, forms, …
> update material2 branch

- README.md
Minor change of humans.txt reference in README.md on line 111.
Thank you.
> docs(readme): fix humans.txt reference

- README.md
<p align="center">
<a href="https://angularclass.com" target="_blank">
</a>
</p>
> feat(Angular2): Free Angular 2 Fundamentals Course

- .travis.yml
- config/karma.conf.js
- src/app/app.e2e.ts
Fixes bug in initial e2e tests
resolves #836
> Fixes initial e2e tests

- config/webpack.common.js
Docs
Explain and link angular2-template-loader
> chore: add comments

- config/spec-bundle.js
Bug fix
* **What is the current behavior?** 
https://github.com/AngularClass/angular2-webpack-starter/issues/901
See also
https://github.com/angular/zone.js/issues/404
Running tests works fine.
> Fix issue #901 (zone.js/dist/proxy-zone issues)

- src/custom-typings.d.ts
tslint was complaining about these things when running `npm run lint`
> fix tslint errors

- README.md
this fixes #867
in response to @gdi2290 comment on #867
> added @types example

- config/helpers.js
clean the helper file
not used code setting around
cleaner code
> checkNodeImport is never used!

- src/main.browser.ts
Remove unused import `ApplicationRef`.
> refactor(main.browser.ts): remove unused import

- config/webpack.common.js
Fix for issue #993 
Warning in webpack during build
No Warning
> fix: Angular2 RC7 dependency warning

- package.json
Cleanup
`@types/corejs` is installed but not used due to recent changes.
Less dependencies, cleaner `package.json`.
> Remove @types/corejs

- src/app/app.module.ts
- src/app/app.service.ts
* **What kind of change does this PR introduce?** Typo fix
* **What is the current behavior?** No change in behavior.
* **What is the new behavior (if this is a feature change)?** No change in behavior.
Renamed `InteralStateType` to `InternalStateType`.
> refactor(app): fix typo in InteralStateType

- package.json
small typo hanging around in package.json
> chore(package) typo

- config/webpack.common.js
> Updated docs

- src/app/+detail/index.ts
- src/app/app.routes.ts
> fix: Rename export for detail module

- index.html
Besides these changes, I also noticed that the file structure is actually outdated but I decided not do anything since there might be a plan for it.
> Typo fixes in index page

- config/github-deploy/index.js
support ssh prototal address for depolying to github pages
> support ssh prototal address

- src/app/app.routes.ts
Removed unused RouterModule import
> Chore(routing): removed unused RouterModule import

- config/webpack.common.js
https://github.com/AngularClass/angular2-webpack-starter/issues/1413
> Fix for bug with CommonsChunkPlugin and Win paths

- config/webpack.test.js
Current resolution is incorrect.
This is a quickfix.
> test: resolve root modules directory in test

- src/app/home/home.component.html
Remove unnecessary HTML code
Code was needed for Material Design, which was removed in #613
> Remove material design leftovers

- config/webpack.github-deploy.js
> fix: load gh-pages late

- src/app/app.component.ts
a little cosmetic change
the Index button is always shown as beeing `active`
it's only `active` when the user is on the index page
> fix: Index button is always 'active'

- config/webpack.common.js
not sure for which branch i should create a pull request
> Updated to support font loaders

- src/main.browser.aot.ts
> 2 pps in bootstrapping

- src/main.browser.ts
> another 2pps

- src/custom-typings.d.ts
* **What kind of change does this PR introduce?** 
Just 	terminate unterminated statement remove warning in the code.
> Terminate unterminated statement

- package.json
Removes @angularclass/conventions-loader npm package.
Clean up.
No changes.
> Remove unused dependency.

- .travis.yml
> Gdi2290 patch 2

- README.md
docs
outdated angular names
the correct angular name without version
> docs(readme): it's just angular

- .travis.yml
fix sass error in travis
sass error in travis
fix travis error
> chore(travis): rebuild node-sass

- .travis.yml
update node
node version 6 is used
use node version 7 
> chore(travis): update node

- .dockerignore
- Dockerfile
- README.md
FEATURE: One of the goal of docker is ability to run project on any machine without **dependency hell**. So to run project we should need only isntalled **OS**, **git** and **docker** (and that's all - no node.js etc.). The proposed solution meets these expectations. We are able to completely automate deployment process (portable on all platforms which support  docker).
In README.md file are included more informations (and instructions).
Current docker file is write in not good way because we need install many dependencies in our host operating system before we are able to run project (like node.js). In fact, if we clone repo …
> FEATURE: Dockerfile which totally automate deployment process

- config/protractor.conf.js
- src/app/app.e2e.ts
- src/app/home/home.e2e.ts
feature - remove control flow from protractor tests
Protractor tests use control flow
Now used async/await functions
https://github.com/AngularClass/angular-starter/issues/1766
> Use async/await instead of control flow in protractor

- .travis.yml
clean, prune, update before install
none
clean, prune, update before install
> chore(travis): prune/clean/update

- README.md
> docs(readme): windows node-pre-gyp

- package.json
> chore(package): update name and links of repository

- src/app/+barrel/+child-barrel/child-barrel.component.ts
- src/app/+detail/+child-detail/child-detail.module.ts
> chore: update logs

- src/app/home/home.e2e.ts
> Fixed component name in describe()

- config/webpack.common.js
> docs: grammar

- package-lock.json
Add package-lock.json file.
It is intended to be committed into source repositories.
https://docs.npmjs.com/files/package-lock.json
No package-lock.json file. It gets generated on ```npm install```
package-lock.json is present in the repo.
> chore(npm): add npm5 package-lock.json.

- Dockerfile
- README.md
- docker-compose.yml
add docker-compose file
- bugfix - fix the missing openssl dependency
- feature - add docker-compose file
- app fail when using docker
- issue fixed
> fix apk dependencies

- package.json
Thanks to https://github.com/almothafar for suggesting a fix
Bug fix
https://github.com/gdi2290/angular-starter/issues/1974
> fix: https://github.com/gdi2290/angular-starter/issues/1974

- config/karma.conf.js
Bug fix
Karma and coverage summary are reported twice.
Karma and coverage summary are reported correctly.
Related to #1994
> Fix to karma reporter reporting twice amount of executed tests
