- tsconfig.json
Update the version of the tsconfig.json to match the TypeScript version
in package.json and fixes the path to lib.dom.d.ts which moved as of TS
version 1.6
This fixes annoying red squiggly line errors in visual studio code (and potentially
other editors) relating to module, experimentalDecorators or emitDecoratorMetadata
not being set.
> Update tsconfig.json for Typescript 1.6

- protractor.conf.js
To get e2e tests running, I had to fix some issues with Protractor/Selenium. First of all I had to adjust the port of the `baseUrl` to `3000` since the webpack dev server is running on this port. 
Then I ran into an issue in which it was impossible to get the WebDriver session started. This is documented [here](https://github.com/angular/angular-seed/issues/251). The [solution](https://github.com/angular/angular-seed/issues/251#issuecomment-129217595) by @josefsalyer worked for me, so I suggest to use it in this repo as well.
> Fix Protractor/Selenium Configuration

- .gitignore
- package.json
- typedoc.json
This PR adds typedoc support for the src/* folder.
It does spit out some errors due to duplicate symbols on some of the angular2 imports (Promise amongst others), but it will parse and process the src folder just fine.
> Add typedoc support

- package.json
Update protractor package version as the current 2.1.0 fails on node 4.1.1+
> Update protractor package version as the current 2.1.0 fails on node 4.1.1+

- examples/rx-autosuggest/bootstrap.ts
- examples/rx-autosuggest/directives/ac-autosuggest.ts
- examples/rx-autosuggest/services/GithubService.ts
- examples/rx-timeflies/components/timeflies.ts
Original examples had
```javascript
import * as Rx from 'rx'
```
This should have been
```javascript
import * as Rx from '@reactivex/rxjs'
```
> Refactor for correct reference to Rx module

- src/app/app.ts
The comment 
```javascript
"You must run these commands for the Http API to work in another process "
```
is confusing. On initial reading it sounds like we want the Http API to run in another process.
Whereas in fact we want these commands to run in another process. So changed to 
```javascript
"You must run these commands in another process for the Http API to work"
```
Also made this clearer in the comments just under onInit().
> Clarified some comments re starting server.

- examples/rx-autosuggest/directives/ac-autosuggest.ts
- examples/rx-autosuggest/services/GithubService.ts
I have fixed the rx-autosuggest example which was broken when using angular2@2.0.0-alpha.44. The example is now working again.
> Fix broken rx-autosuggest example

- examples/large-app/bootstrap.ts
- examples/large-app/components/app.ts
- examples/large-app/components/rxjs_examples/rxjs-examples.ts
- examples/large-app/pipes/RxPipe.ts
- examples/large-app/pipes/pipes.ts
- examples/large-app/services/example-service.ts
- examples/large-app/services/services.ts
- examples/rx-autosuggest/directives/ac-autosuggest.ts
Went through large-app to the point where it would compile and run to display main banner.
Still some things not working – see commented out lines in large-app/bootsrap.ts
> Refactor to fix broken links in large-app

- examples/large-app/bootstrap.ts
- examples/large-app/components/app.ts
- examples/large-app/components/rxjs_examples/rxjs-examples.ts
- examples/large-app/pipes/RxPipe.ts
- examples/rx-timeflies/components/timeflies.ts
I have fixed several issues with angular2@2.0.0-alpha.44. Furthermore I have fixed a broken import (see https://github.com/angular-class/angular2-webpack-starter/commit/a49383969f3729a73b1ac067c41e253b95556d53#commitcomment-13901195).
I also changed an import statement to keep the syntax the same across the application, because webpack complained about the import: 
> There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
There are still some issues with the 'search github' and 'todo' components, but the router does work again and at least webpack compiles without an error. This PR fixes …
> Fix: examples/large-app

- examples/rx-autosuggest/app.ts
- examples/rx-autosuggest/bootstrap.ts
- examples/rx-autosuggest/components/search-github.ts
- examples/rx-autosuggest/directives/ac-autosuggest.ts
- examples/rx-autosuggest/services/GithubService.ts
- examples/rx-draggable/bootstrap.ts
- examples/rx-draggable/components/drag-element.ts
- examples/rx-timeflies/app.ts
- examples/rx-timeflies/bootstrap.ts
- examples/rx-timeflies/components/timeflies.ts
- examples/rx-timeflies/services/Message.ts
BINDINGS will be deprecated soon, so we use PROVIDERS instead. Also remove unnecessary @View
> chore(rx-examples): Rename BINDINGS to PROVIDERS in rx-examples

- src/app/app.ts
- test/app/app.spec.ts
- test/injector.spec.ts
- test/sanity_test.spec.ts
I have followed the discussion in https://github.com/AngularClass/angular2-webpack-starter/issues/124 and got tests up and running. I have added some simple tests for directives and components. This should be a good starting point for adding more tests that demonstrate also tests of other facets of ng2.
> Add some simple tests to demonstrate testing directives and components

- spec.bundle.js
- src/app/app.ts
Also with recent builds, we no longer need to specify `CORE_DIRECTIVES` or `FORM_DIRECTIVES` as those come out of the box now.
> chore(Cleanup): removed unused 'View' and using the recently renamed ngOnInit now with alpha.47

- spec-bundle.js
Unit tests did not run after a fresh clone.
spec-bundle.js was requiring 'es6-shim', updating to core-js appears to have solved this for me.
> spec-bundle.js now requires core-js instead of es6-shim

- README.md
In addition to the installation instructions in the readme, I had to run `typings install` to make the app work properly.
> docs(readme): include `typings install`

- webpack.config.js
See #158.
Changes files sizes from this:
```
Asset     Size  Chunks             Chunk Names
app.js   4.8 MB    0, 2  [emitted]  app
vendor.js  5.45 MB    1, 2  [emitted]  vendor
common.js  3.65 kB       2  [emitted]  common
app.map  5.11 MB    0, 2  [emitted]  app
vendor.map  5.91 MB    1, 2  [emitted]  vendor
common.map  3.68 kB       2  [emitted]  common
```
To this:
```
Asset     Size  Chunks             Chunk Names
app.js  7.31 kB       0  [emitted]  app
vendor.js   652 kB       1  [emitted]  vendor
common.js   4.8 MB       2  [emitted]  common
app.map  8.14 kB       0  [emitted]  app
vendor.map   800 kB       1  [emitted]  vendor
common.map  5.11 MB       2  [emitted]  common
```
> Include vendor chunk when creating common chunk

- src/bootstrap.ts
- src/vendor.ts
Due the update from version 2.0.0-alpha.52 to 2.0.0-alpha.53 there are deprecated versions of imports. I added the new imports.
> update deprecated imports to 2.0.0-alpha.53

- package.json
Removes warning:
```
npm ERR! peerinvalid The package es6-shim@0.34.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.0 wants es6-shim@^0.33.3
```
As mentioned in #162.
> Change es6-shim version to satisfy angular@2.0.0-beta-0

- tsconfig.json
After having errors on npm start, was a problem related to "./test/**/*.ts" missing the comma after on the tsconfig.json
> Update tsconfig.json error on missing the comma

- README.md
- package.json
- webpack.config.js
- webpack.prod.config.js
https://github.com/AngularClass/angular2-webpack-starter/compare/master...samvloeberghs:master#diff-04c6e90faac2675aa89e2176d2eec7d8L49:
When you follow the guide and you install typings globally, you don't need to reference it into node modules, right?
https://github.com/AngularClass/angular2-webpack-starter/compare/master...samvloeberghs:master#diff-04c6e90faac2675aa89e2176d2eec7d8L54
I just followed you guys setup description and http://0.0.0.0:3000 doesn't work by default on a Windows machine. So I've added http://localhost:3000.
Grtz
> updated readme

- package.json
- webpack.config.js
Currently, source mapping for external packages are not mapped.
Stepping into code of external packages will step into actual runtime code as supplied to the browser.
```
import {Directive, Component, ElementRef, Renderer} from 'angular2/core';
/*
* Directive
* XLarge is a simple directive to show how one is made
*/
@Directive({
selector: '[x-large]' // using [ ] means selecting attributes
})
export class XLarge {
constructor(element: ElementRef, renderer: Renderer) {
// simple DOM manipulation to set font size to x-large
// `nativeElement` is the direct reference to the DOM element
// element.nativeElement.style.fontSize = 'x-large';
// for server/webworker support use the renderer
debugger;
renderer.setElementStyle(element.nativeElement, 'fontSize', 'x-large');
}
}
```
In for code …
> feat(sourcemap): Proper source maps for 3rd party packages

- webpack.prod.config.js
mangling is broken in Angular 2 beta.1 as described in #262. That's why it should be disabled until Angular 2 beta.2 is out.
> disable mangle for now

- karma.conf.js
- package.json
To keep track of larger projects, I would like to suggest to use the karma-mocha-reporter and summarize the coverage report. 
If you want to have a look at the coverage per file, the HTML output is much more convenient then displaying the line numbers in the console.
**Before:**
**After:**
> Optimize console output for testing

- README.md
Removed the instruction to install typescript typings as there is already a postinstall npm script that will do that.
> Removed typescript typings install from quick start - Fixes #309

- src/app/directives/router-active.ts
This fix the directive that put a 'active' class on active link.
In a case with a 2 level of routeConfig the second level is not correctly define.
Fixed version
http://plnkr.co/edit/vleQ7C7Z0VBwrwx46UO3?p=preview
Original version
http://plnkr.co/edit/3ZbRYYzIxiiliP2Gbzm7?p=preview
> Fix directive for route active

- src/custom-typings.d.ts
`src/custom-typings.d.ts[46, 4]: missing semicolon`
> missing semicolon

- package.json
Regarding to this [issue](https://github.com/angular/angular/issues/7081) parse5 has to be added to the package.json in an older version to make webworkers work.
> Webworker are broken without parse5

- src/app/app.ts
Hi, 
In trying to build for prod, I get a fail concerning a missing space between the class App and the curly brace.
> src/app/app.ts
> [72, 17]: missing whitespace
> Fix a missing space in the App class declaration.

- webpack.prod.config.js
remove filename from CommonsChunkPlugin to use filename in output with chunkhash
build:prod generates ['main', 'vendor', 'polyfills'].bundle.js
build:prod generates ['main', 'vendor', 'polyfills'].[chunkhash].bundle.js
It will allow server to cache js files forever.
> remove filename from CommonsChunkPlugin to use filename in output with chunkhash

- webpack.config.js
- webpack.prod.config.js
- webpack.test.config.js
I spent my time to make a present for you: I've annotated webpack configuration with docs.
Also I've removed unnecessary commas. 
It's the same as before;
It's the same as before;
Enjoy it!
> A little present for AngularClass. Webpack configuration documentation

- src/app/app.spec.ts
- src/app/home/home.spec.ts
Fixes `app` and `home` unit tests. 
Unit tests are are currently failing due to new dependencies not being provided.
```
npm run test
...
SUMMARY:
✔ 4 tests completed
✖ 4 tests failed
FAILED TESTS:
App
✖ should have a url
PhantomJS 2.1.1 (Mac OS X 0.0.0)
Failed: No provider for AppState! (App -> AppState)
Home
✖ should have default data
PhantomJS 2.1.1 (Mac OS X 0.0.0)
Failed: No provider for AppState! (Home -> AppState)
✖ should have a title
PhantomJS 2.1.1 (Mac OS X 0.0.0)
Failed: No provider for AppState! (Home -> AppState)
✖ should log ngOnInit
PhantomJS 2.1.1 (Mac OS X 0.0.0)
Failed: No provider for AppState! (Home -> …
```
> fix(tests): Provide state dependencies

- README.md
- config/webpack.dev.js
- nitrous-post-create.sh
- nitrous.json
- src/index.html
This allows developers to conveniently run this starter kit in the "cloud" (where cloud == [Nitrous](https://www.nitrous.io/)).
N/A.
I've added a button to the readme that users can click to create an Ubuntu-powered development environment with the angular2-webpack-starter repository cloned and with its dependencies setup.
I'm featuring angular2-webpack-starter on [this page](https://www.nitrous.io/quickstarts/) because it's a great use case for Nitrous.
> Add support for running on Nitrous

- config/spec-bundle.js
Bug fix: test failed when service use map from rxjs
Failed: undefined is not a constructor 
Test passed
> add rxjs dependencies for test

- config/helpers.js
- config/webpack.prod.js
Bug Fix
`npm run build:prod` fails (issue described in #473)
Fixes #473, builds with gzip and compression level of 9 (defaults of compression-webpack-plugin)
N/A
> Don't pass default options and remove redundant helpers. Fixes #473

- config/webpack.common.js
- config/webpack.dev.js
- config/webpack.prod.js
Build config update
#453 has a single metadata config for dev and prod, thereby forcing `development` environment even on prod builds.
Prod and dev configs now maintain separate metadata.
> Separate webpack config metadata for dev and prod

- package.json
Reintroduces bin to path for `npm test` similar to https://github.com/AngularClass/angular2-webpack-starter/commit/216fa0db6c7e4092cfdf22b25aafb9b0bdfaba95
```
Error: Cannot find module '/Users/user/angular2-webpack-starter/karma'
at Function.Module._resolveFilename (module.js:339:15)
at Function.Module._load (module.js:290:25)
at Function.Module.runMain (module.js:447:10)
at startup (node.js:139:18)
at node.js:999:3
npm ERR! Test failed.  See above for more details.
```
Tests run.
> chore(package.json): Update karma bin path

- config/webpack.test.js
The comments of the webpack test say that html is loaded but css is loaded. The sam is for css where the comment says it loads css but it loads html. This pull Requests fixes this.
Same as before
Same as before
In the comment of the file it sayed that the loader load `*.css` but it actually loaded `.html`.
Same is for the `*.html` comment it loads `.css` files
> [Quick Fix] Fixed small typo

- config/webpack.test.js
The current step does not allow step through debugging for TS files or any files actually.
The spec-bundle.js file has no .map file so browser support does not allow debugging.
The solution is simple and taken from the karma-webpack README.
https://github.com/webpack/karma-webpack#source-maps
Thanks.
> Step-through debugging for tests in Karma

- src/polyfills.ts
Replaced core-js default import in favour of specific deps import
Right now the core-js library is imported as default (Includes all features, standard and non-standard).
Only import from core-js the es6 and es7 reflect shims.
> Replaced core-js default import in favour of specific deps import

- config/webpack.dev.js
This is a bug fix. The merged metadata from webpack.common.js wasn't exported after being merged. This resulted in index.html not being able to read environment variables.
Currently, metadata that was merged isn't available, only the original metadata from webpack.common.js
#496
This exports the data, as I believe was intended from referencing webpackConfig.metadata.ENV on 
[index.html](https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/index.html) line 55. 
webpack.prod.js doesn't export the metadata either, is this something we might want for using within index.html?
> Metadata dev fix

- src/main.browser.ts
Feature: Register ENV_PROVIDERS after PROVIDERS so that default providers can be override by ENV_PROVIDERS
> change the order of providers

- config/spec-bundle.js
simplification
VSC will complain if you leave the extension because it thinks that you want to load the .d.ts and will put a red wiggle on it.
VSC will be happy, apart from that, no issue.
> chore: remove extensions at spec-bundle

- config/webpack.common.js
It is a chore, simplifies config.
Doesn't change current behavior.
Doesn't change current behavior.
You don't need to specify the `main` in here. What webpack is going to do is create a hierarchy (making vendor to be the parent of `main`) and having that `main` there won't add any value. The minChunks is not needed for the current config.
Also, you could drop the reverse helper and just swap the chunks positions.
FWIW, Webpack is smart enough to order the chunks like: polyfills -> vendor -> main so for HtmlWebpackPlugin there is no real need …
> chore: simplify usage of CommonsChunkPlugin

- config/webpack.dev.js
- package.json
When upgrading copy-webpack-plugin, an error stops webpack-dev-server if devServer.outputPath is not given
> Upgrade copy-webpack-plugin to 2.1.3

- config/protractor.conf.js
remove unused selenium jar declaration
Since we have `directConnect` set, the `seleniumServerJar` is ignored.
more information: https://github.com/angular/protractor/blob/master/docs/server-setup.md#connecting-directly-to-browser-drivers
no more unnecessary jar declaration
> remove selenium jar path

- src/app/about/about.component.ts
- src/app/app.component.ts
- src/app/home/home.css
- src/app/home/home.html
- updates the nav bar to current material standard
- adds styles for the buttons on the nav bar to make the active state more obvious
- moves the reload instructions to the about page
- change layout for the footer
- change layout of page to make sections clearer
- add margins to cards
- use multiple forms of css and alternate margins to illustrate isolating styles
> Style update

- src/app/about/about.component.ts
- src/app/about/about.spec.ts
- src/app/app.component.ts
- src/app/app.service.ts
- src/app/app.spec.ts
- src/app/home/home.component.ts
- src/app/home/home.spec.ts
- src/app/home/title/title.service.ts
- src/app/home/title/title.spec.ts
- src/app/home/x-large/x-large.directive.ts
- src/app/home/x-large/x-large.spec.ts
- src/app/index.ts
- src/app/router-active/router-active.directive.ts
- src/main.browser.ts
- src/platform/browser/angular2-material2/index.ts
- src/platform/browser/directives.ts
- src/platform/browser/pipes.ts
- src/platform/browser/providers.ts
- src/platform/environment.ts
Update to conform to [Angular Style Guide](https://angular.io/styleguide)
some source files violate Coding Conventions rules on Import Destructuring Spacing (03-05) and Import Line Spacing (03-06)
source conforms to style guide rules 03-05 and 03-06
Style 03-05: Import Destructuring Spacing
-Do leave one whitespace character inside of the import statements' curly braces when destructuring.
-Why? Whitespace makes it easier to read the imports.
Style 03-06: Import Line Spacing
-Do leave one empty line between third party imports and imports of …
> Style: 03-05 and 03-06

- config/webpack.common.js
`chunksSortMode: 'dependency'` should sort your injects correctly, without helper function, also will be the default behavior in webpack2
> simplify HtmlWebpackPlugin options

- tsconfig.json
[these comments](https://github.com/AngularClass/angular2-webpack-starter/commit/fe6a1def8e071ed3548ada3847b2945ae338a596#commitcomment-17516133)
typing errors and `duplicate identifier` issues
point to moved typings/index.d.ts changed in 1.0.4 update
> tsconfig.json fix for 1.0.4 typings release

- config/helpers.js
- config/webpack.common.js
- src/index.html
Bug fix
When creating a build using `build:dev` the index.html request a javascript resource **webpack-dev-server.js**.
**webpack-dev-server.js** is used by `webpack-dev-server` which also returns it (the resource).
Since a build is intended to run in a different web server it will always 404.
Do not include 'webpack-dev-server.js` script request in builds, only include it when running udner `webpack-dev-server`
The current implementation uses **ENV** to determine if were in development mode, if so include `webpack-dev-server.js`. A build …
> fix: webpack-dev-server.js will 404 on build:dev

- src/app/app.service.ts
resolves issue #673 
if the property is of type boolean and value false then the whole state object is returned
the property value is returned, even if the value is false
this resolves the issue #673, that boolean properties with value 'false' are not returned.
> bool false value not returned, Resolves issue #673

- config/head-config.common.js
- config/helpers.js
- config/html-elements-plugin/index.js
- config/webpack.common.js
- src/index.html
feature
head tags are hardcoded in `index.html` (specially assets
head tags are created dynamically from a JS module.
This behavior also cleans up the index.html file.
A step for `github` pages support #645
> feat(configurable-head-tags): allow configuring head tags in a js module

- config/github-deploy/index.js
- config/webpack.common.js
- config/webpack.github-deploy.js
- package.json
feature
Same as ng-cli, an option to deploy to github into the `gh-pages` branch.
This feature requires some modifications to `index.html` and an additional webpack config file `webpack.github-deploy.js`. 
Dependes on #643 
This PR adds the `gh-pages` npm packages to the devDependencies.
`gh-pages` has a lot of option to customise the operation, for this initial PR I chose to allow a limited set of configuration not to confuse.
Use can change the git remote origin and a constant commit message, see `webpack.github-deplot.js`
> GitHub deployment script into gh-pages - dev or prod builds.

- package.json
FIX globbing of ts files on osx
Will not go deeper than 2 levels
Will scan all the files
> fix globbing problems on tslint, on osx wouldn't correctly glob

- README.md
Simple readme fix, to a command that works.
`npm run typings-install` yields:
> npm ERR! missing script: typings-install
Typings will be installed correctly.
...since there's no `typings-install` script @ package.json.
> docs(readme): fix typings install command

- config/webpack.dev.js
Enhancement
Production configuration lets you configure host and port, but dev configuration does not. It defaults to localhost and port 3000.
Fixes issue:
https://github.com/AngularClass/angular2-webpack-starter/issues/821
And partially:
https://github.com/AngularClass/angular2-webpack-starter/issues/186
Now to run dev server on a VM you can just run
PORT=8081 HOST="0.0.0.0" npm run server:dev:hmr
or if you're using "forever"
PORT=8081 HOST="0.0.0.0" forever start -v --minUptime 1000 --spinSleepTime 1000 -c "npm run server:dev:hmr" ./
I'm …
> Update webpack.dev.js to take respect optional HOST/PORT params

- tsconfig.json
Since Typescript2 its possible to use es2015 declarations with `target: es5` specified.
And we can drop `@types/core-js` from deps.
See: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#including-built-in-type-declarations-with---lib
> use typescript declarations for es2015

- src/app/about/about.spec.ts
- src/app/app.spec.ts
- src/app/home/home.spec.ts
- src/app/home/title/title.spec.ts
- src/app/home/x-large/x-large.spec.ts
Update tests framework 
per angular rc4 update deprecated test functions
> chore: update deprecated test functions

- package.json
Adds string-replace-loader as a devDependency in package.json
Errors are thrown when building - since string-replace-loader is missing.
Fixes the errors.
I like cheese.  :-)
> Include string-replace-loader as devDependency

- src/app/about/about.spec.ts
- src/app/home/title/title.spec.ts
- src/app/home/x-large/x-large.spec.ts
* **What kind of change does this PR introduce?** : Bug fix
When running tests you get errors like:
```
ERROR in [default] ...GitHub/_forks/angular2-webpack-starter/src/app/about/about.spec.ts:1:9
Module '"C:/Users/azureuser/Documents/GitHub/_forks/angular2-webpack-starter/node_modules/@angular/compiler/testing"' has no exported member 'TestComponentBuilder'.
```
No errors.
> Fix { TestComponentBuilder } for latest @Angular RC5

- config/spec-bundle.js
* **What kind of change does this PR introduce?** (fix)
Since `Angular RC.5` testing API [has changed](https://github.com/angular/angular/commit/fa47890). This PR replaces obsolete `setBaseTestProviders` with `TestBed.initTestEnvironment`
> Replace obsolete setBaseTestProviders with TestBed.initTestEnvironment

- config/webpack.common.js
- src/app/about/about.component.ts
- src/app/about/about.spec.ts
- src/app/app.module.ts
- src/app/app.service.ts
- src/app/app.spec.ts
- src/app/environment.ts
- src/app/home/home.component.ts
- src/app/home/home.spec.ts
- src/app/home/title/title.spec.ts
- src/custom-typings.d.ts
Added missing type information to compile in case of `noImplicitAny` is set to true
If you set `noImplicitAny` to true, you have many TypeScript errors.
Compiled without errors when `noImplicitAny` is set to true.
See https://github.com/angular/angular-cli/issues/107#issuecomment-164809092
> Add missing type information to compile in case of `noImplicitAny`

- config/helpers.js
It's should fix issue #757
Like described in issue #757
Exec will return to ["webpack-dev-server"] in case if we run webpack-dev-server
example:
/webpack-dev-server/.exec('D:\angular2-webpack-starter\node_modules\webpack-dev-server\bin\webpack-dev-server.js')  //return  ["webpack-dev-server"] ,
so whole expression will be like:
function isWebpackDevServer() {
'D:\angular2-webpack-starter\node_modules\webpack-dev-server\bin\webpack-dev-server.js' && !!["webpack-dev-server"]
}
what is true;
> isWebpackDevServer() fix for windows, issue #757

- package.json
**Dependency update**
This removes the need for forked version of  string-replace-loader
> Update string-replace-loader to 1.0.5

- config/karma.conf.js
Not sure when the api changed, but `webpackServer: { noInfo: true },` doesn't work anymore. This uses 
`webpackMiddleware: { stats: 'errors-only'}` to accomplish the same goal.
When running tests, built modules are output to the console.
Karma-webpack will only output errors during code compile for tests.
Set wepack to only output errors during testing
> Set karma-webpack to only log errors

- tsconfig.json
A **configuration file change.**
This change is merely change in tsconfig from an empty array to an empty object to conform with proper tsconfig compiler options. Just to remove type error warnings in coding programs.
Currently the code is `paths: []`
Proposing a change to `paths: {}`
In the tsconfig.json the property `compilerOptions.paths` should be an object and not an array.
See https://www.typescriptlang.org/docs/handbook/compiler-options.html
> Update tsconfig.json paths property to object

- README.md
docs update
The old way is 
```ts
styles: [
require('./app.component.scss')
],
```
The way now is 
```ts
styleUrls: ['./app.component.scss'],
```
> docs(readme): update the way to use sass/scss

- src/assets/manifest.json
removed ignored `density` attribute from manifest.json
ignored attribute `density` is present in `manifest.json`
attribute `density` is removed from manifest.json
According to [Google](https://developers.google.com/web/updates/2014/11/Support-for-installable-web-apps-with-webapp-manifest-in-chrome-38-for-Android), `density` will be ignored from manifest.json:
> Please note, there used to be a dedicated “density” field in the manifest spec, this has been removed from the Spec and the implementation in Chrome. If it is defined in your manifest …
> removed ignored property density from manifest.json

- config/webpack.common.js
Bug fix
#1070 humans.txt and robots.txt get copied from the assets directory to the output assets directory.
All files in the assets folder get copied to dist/assets except for humans.txt and robots.txt.
humans.txt and robots.txt get copied from the assets folder to the root dist/ folder.
Fixes issue #1070
The standard for humans.txt and robots.txt says that they should be available from the root of the application. This change will make sure that they get copied from the assets folder to the dist/ root instead of to dist/assets.
> Copy humans.txt and robots.txt to dist/

- package.json
Remove unused dependencies from package.json
``@angularclass/webpack-toolkit``
``@angularclass/request-idle-callback``
Are these still used? Can't find any reference to it in the current version.
dependencies in
dependencies out
> Remove unsed dependencies: webpack-toolkit, request-idle-callback

- index.html
docs update
Showing warning that Angular 2 is not ready.
Doesn't show the warning about Angular 2 is not ready.
Removed a warning and link to [Is Angular 2 Ready?](https://splintercode.github.io/is-angular-2-ready/).
> Remove warning about Angular 2 is not ready yet.

- .travis.yml
- config/karma.conf.js
Uses [yarn](https://yarnpkg.com) in TravisCI to speed up build process.
Uses `npm` to install dependent packages.
Uses `yarn` to install dependent packages.
> Using yarn in TravisCI to speed up CI

- .travis.yml
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
CI Changes
- **What is the current behavior?** (You can also link to an open issue here)
Travis executes Karma Spec test only
- **What is the new behavior (if this is a feature change)?**
- Webpack is spun up in a forked process
- Karma test run as usual
- Protractor e2e Tests are executed prior to the Docker build
- **Other information**:
Resolves #1113
> ci(travis): Enable e2e test execution in Travis CI

- tslint.json
Fixes #1161
TSLint fails, breaking Karma tests.
TSLint runs, allowing Karma tests to run.
Deprecated configuration options were breaking Karma tests
Would not be necessary if pull request #1105 is approved.
> Remove deprecated TSLint configuration options

- config/html-elements-plugin/index.js
Bug fix
Script tags are not properly closed when included in the html-elements-plugin
Script tags are now properly closed
My solution is a bit messy and I'm not sure whether or not the original behavior was intended. Anyways this was useful for me since I wanted to include a library from a CDN and have it in the same configuration file as the CSS and fonts loaded from CDNs.
> Close script tags in html-elements-plugin

- config/webpack.test.js
Workaround for bug outlined in #1188 
Further investigation required for the behavioral change between `use:` & `loader:` in `webpack.config.js`
//cc @gdi2290 @katallaxie
> fix(sourcemaps): #1188 - temp fix for sourcemap errors

- src/app/environment.ts
Fix a bug that appears with Angular2.2 when using a production bundle.
Currently, when launching a prod bundle, the app doesn't work because of an `Cannot convert undefined or null to Object` that occurs in the `disableDebugInfo` function of Angular2.2.
This function tries to delete `window.ng.provider`, but at the moment of the call of the `disabledDebugInfo` function, the `ng` property has not yet been created in the `window` object because Angular is not yet initialized.
We now wait for Angular to be initialized before disabling debug info and enabling production …
> fix(angular2.2): wait for angular before disabling debug info

- config/webpack.common.js
- package.json
Renamed `angular2-router-loader` devDependency to `angular-router-loader`
Updated to angular-router-loader
> chore(deps): Renamed angular2-router-loader package

- package.json
Chore - Work around for `awesome-typescript-loader` issue.
- Relavent issue: https://github.com/s-panferov/awesome-typescript-loader/issues/293
Relates to #1249
> chore(package): pins TypeScript version to 2.1.1

- README.md
- src/app/home/home.component.html
Docs update
Two links point to an old [material2 branch](https://github.com/AngularClass/angular2-webpack-starter/tree/material2) which no longer exists, so both links are broken.
Broken links to nonexistent branch "material2" are removed.
N/A
> Fix broken links

- config/webpack.prod.js
Chore cleanup
Dedupe Plugin is [removed](https://github.com/webpack/webpack/commit/91cbb4c28879b7836c5105d9feac81bc2dfeb5ac) from webpack in [v2.2.0-rc.3](https://github.com/webpack/webpack/releases/tag/v2.2.0-rc.3), so there is no need to have it in configuration.
No Dedupe Plugin in config. [Use](https://github.com/webpack/webpack/issues/3463) `npm dedupe` for deduplication.
N/A
> chore(config): remove dedupe plugin from webpack config

- config/webpack.dev.js
It's correcting to use [file] instead [name] in order to support work together with ExtractTextPlugin souremaps
Inspired by:
https://github.com/webpack/extract-text-webpack-plugin/issues/119#issuecomment-181584004
> refactor sourceMapFilename to use file

- config/helpers.js
Fixes #1259
Style improvement.
Currently the `root` function in the `helpers` module has some unpleasant code deemed necessary for compatibility reasons. It manipulates the arguments object via `Array.prototype.slice.call` and rebinds its actual argument which is a bad practice and is also confusing since the argument's value is ignored and it is effectively used as a variable.
Cleans up the function and reduces code size.
> Remove direct manipulation of the arguments object

- package.json
- tsconfig.json
- tsconfig.webpack.json
TypeScript v2.1.5 has several problems in Windows, which don't affect Mac or Linux. This patch introduces workarounds so builds pass on all operating systems.
- Resolves #1353 
- Resolves #1371 
- Minor dependency updates
> Work around TypeScript 2.1.5 bugs in Windows

- config/webpack.common.js
- package.json
Support the [Dynamic import proposal](https://github.com/tc39/proposal-dynamic-import) [TC39 Stage 3] as a loader (codegen).
The import() construct is supported in webpack from 2.1.0-beta28
> "async-system" is deprecated in webpack 2 and removed in webpack 3.
Moving to 2.0.0 requires a subtle change in the TS loader order.
**Dev's that just upgrade the packages will have some trouble locating this change in the configs so we might expect some noise**
Reason for change:
Typescript transform `import(...)` syntax into something else.
To use `ng-router-loader` with `async-import` code generator the `ng-router-loader` must
run **AFTER** the TS compiler (e.g: awesome-typescript-loader), that is in a lower index in the loaders array. If it runs before, TS will see the `import(...` expression and …
> feat: use import() construct via ng-router-loader@2.0.0

- package.json
feature - add --open to webpack-dev-server
does not open on `npm start`
webpage will open on `npm start`
> open page on dev start

- config/webpack.dev.js
The webpack.dev.js file from config has an invalid format. There are missing commas.
> Fix webpack.dev.js json format error

- config/webpack.test.js
We don't need `path` module as it is done using `helpers.root`. see [this](https://github.com/AngularClass/angular2-webpack-starter/commit/1ea8b71fe2bc1debe608eb604cb18b35ddda8884)
> test: remove unused module

- config/webpack.prod.js
- package.json
As per `extract-text-webpack-plugin` version [2.0.0-rc.3](https://github.com/webpack-contrib/extract-text-webpack-plugin/releases/tag/v2.0.0-rc.3) following are deprecated.
- `fallbackLoader` is replaced with `fallback`
- `loader` is replaced with `use`
You will get following message on console while building for production `npm run build:aot:prod`
> chore(package): update extract-text-webpack-plugin to version 2.0.0-rc.3

- config/webpack.test.js
This commit fixes #1016.
When a SASS file `@includes` another, then when unit tests are run the following error might be produced:
Uncaught Error: Expected 'styles' to be an array of strings
To reproduce:
```
git clone -b sass-import-unit-test-issue https://github.com/mikechamberlain/angular2-webpack-starter.git
npm install
npm run test
```
> fixes #1016

- README.md
#1414 says Material2 branch has been closed. So I have updated the readme for that.
Docs Update for Readme.md
Links to wrong material2 branch results in 404 on Github.
The link is removed no branch is present in the repo, so no reference to material2.
> Updated readme for Material2 branch

- config/webpack.common.js
feature
mock-data files being copy in prod build
mock-data files not being copy in prod build
I discovered it's very useful to use mock-data files both in development and test, but it's bit annoying when publishing to prod, these files usually unnecessary.
>  feat(webpack): ignoring mock-data dir when prod

- package.json
Bug fix
Now `npm run clean` sript fails in npm 5.
This commit fixes npm 5 failing.
> Fix npm cache clean for running on npm 5

- config/protractor.conf.js
from https://github.com/angular/protractor/blob/master/docs/browser-setup.md#using-headless-chrome
Feature
Chrome
Chrome Headless
Add ability to use Chrome headless mode
> Add ability to use Chrome headless mode in prod (instead of PhantomJS)

- .github/CONTRIBUTING.md
- README.md
- config/webpack.test.js
- src/polyfills.browser.ts
It updates old repository name (`angular2-webpack-starter`) in README.md and comments by replacing it by `angular-starter`.
It links to old name in several places.
none
> docs: repository name update

- config/webpack.common.js
- config/webpack.test.js
- package.json
It removes `json-loader` according to [official webpack guide](https://webpack.js.org/guides/migrating/#json-loader-is-not-required-anymore).
For `json-loader@0.5.6` it was throwing the following error several times in CLI and browser console:
Although was fixed in 0.5.7
Behavior remains exactly the same, but the config is slighter.
> chore(config): remove json-loader as no longer needed

- config/webpack.common.js
- package.json
Now when with the AOT cleanup loader there is no need to use resourceOverride and it is not recommened for use as it produced some
side effects with assets.
> chore: upgrade ngc-webpack to 3.2.0 and remove resourceOverride

- config/webpack.dev.js
Allow's overriding webpack dev server public property. I use it in my case where in eclipse che it assigns an ephemeral port, and my dev machine is another one on the network, 10.0.0.1 (or dev in /etc/hosts) not 127.0.0.1. I can then inject with a macro ie `PUBLIC=dev:${server.3000.port} npm run start`
It's always port 3000 and HOST doesn't give us hostname choice, just bind ip
Defaults to undefined and causes no change. It allows above.
> add PUBLIC env var for webpack dev server's public property

- config/webpack.common.js
this plugin must come after the HtmlWebpackPlugin just as the README of it suggests
bug fix
the plugin is before the HtmlWebpackPlugin
the plugin comes after the HtmlWebpackPlugin
the read me of the plugin has specified that this plugin must come **after** the HtmlWebpackPlugin and the order is important
> change order of ScriptExtHtmlWebpackPlugin

- config/webpack.dev.js
fixes #1859 
uses PUBLIC env var which conflicts with windows
uses PUBLIC_DEV instead
> change env var from PUBLIC to PUBLIC_DEV #1859

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/home/home.component.spec.ts
- src/app/home/home.e2e.ts
- src/app/home/title/title.service.spec.ts
- src/app/home/title/title.service.ts
- src/app/home/x-large/x-large.directive.spec.ts
Feature - Upgrading to HttpClient APIs instead of the deprecated Http
Http API is used , this is deprecated in Angular 5 - hence we should avoid using it. 
HttpClient API used for services and tests
Also it reduces one additional dependency of @angular/http in the application payload
> HttpClient API upgrade instead of deprecated Http

- Dockerfile
Bug fix
Docker image does not build
Docker image builds
Seems like the base docker image have moved forward and the specific version of openssl requested couldn't be installed cleanly on top of it.
> fix: Bumped openssl version in docker to make image buildable

- Dockerfile
docs update
Updated comments as the new Dockerfile uses multi-staged build feature of the Docker now.
> Updated comments in the Dockerfile

- Dockerfile-dev
- docker-compose.yml
Fix #2026 
#2026
Now after `docker-compose up`, user can access the page at `localhost:3000`
> Fixed docker-compose up
